### ISSUE TITLE
What's the difference between casdoor-spring-boot-starter and casdoor-spring-boot-example ?

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor-spring-boot-example#5]
https://github.com/casdoor/casdoor-spring-boot-example

https://github.com/casdoor/casdoor-spring-boot-starter

**Comment by seriouszyx** [comment]
The manual configuration like [CasdoorSdkConfig](https://github.com/casdoor/casdoor-spring-boot-example/blob/master/src/main/java/org/casbin/casdoor/springboot/example/config/CasdoorSdkConfig.java) and [CasdoorSdkProperties](https://github.com/casdoor/casdoor-spring-boot-example/blob/master/src/main/java/org/casbin/casdoor/springboot/example/config/CasdoorSdkProperties.java) is required by developers for casdoor-spring-boot-example based on casdoor-java-sdk. But for the version based on casdoor-spring-boot-starter, developers can use the Service directly, instead of getting the configuration first and then creating the Service object.

Casdoor-spring-boot-example based on casdoor-java-sdk (now): 

![image](https://user-images.githubusercontent.com/33992371/142750589-42f85ef4-12f6-4854-9d13-e4d2d1310749.png)

Casdoor-spring-boot-example based on casdoor-spring-boot-starter (Planned): 

![image](https://user-images.githubusercontent.com/33992371/142750548-4141f6a5-9243-42bf-9370-35546b8679c0.png)

**Comment by hsluoyz** [comment]
> Casdoor-spring-boot-example based on casdoor-spring-boot-starter (Planned):

@seriouszyx any update?
